version: '3'

services: 
  db:
    image: postgres
  app:
    build: .
    command: bash -c "rails db:create; rails db:migrate ; rails db:seed ; bundle exec rails s -p 3000 -b '0.0.0.0' -e 'development'"
    environment:
      - PGUSER= 'postgres'
      - PGHOST= 'db'
    volumes: 
      - .:/ZooLand
    ports:
      - "3000:3000"
    depends_on:
      - db